create table user (
    id bigint generated by default as identity unique,
    username varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);

insert into User (id, username, password) values (1, 'aacs', 'aacs');